---
title: "XAI3"
date: "`r Sys.Date()`"
output: html_document
---

# 1. One dimensional Partial Dependence Plot
```{r}
#install.packages("randomForest")
#install.packages("pdp")
library(randomForest)
library(pdp)
library(ggplot2)

data = read.csv('Datos/hour.csv')

data$season_winter <- ifelse(data$season == 1, 1, 0)
data$season_spring <- ifelse(data$season == 2, 1, 0)
data$season_summer <- ifelse(data$season == 3, 1, 0)

data$MISTY <- ifelse(data$weathersit == 2, 1, 0)

data$RAIN <- ifelse(data$weathersit %in% c(3,4), 1, 0)

data$temp <- (data$temp) * (39-(-8)) + (-8)

data$hum <- data$hum * 100

data$windspeed <- data$windspeed * 67

data$dteday <- as.Date(data$dteday)
start_date <- as.Date("2011-01-01")
data$days_since_2011 <- as.numeric(data$dteday - start_date)


model_data <- data[, c("workingday", "holiday", "season_winter", "season_spring", 
                           "season_summer", "MISTY", "RAIN", "temp", "hum", 
                           "windspeed", "days_since_2011", "cnt")]


```

```{r}
# Fit Random Forest model
rf_model <- randomForest(cnt ~ days_since_2011 + temp + hum + windspeed, data = model_data, ntree = 500)
```


```{r}
# PDP for days since 2011
pdp_days <- partial(rf_model, pred.var = "days_since_2011", grid.resolution = 100)

# Create a ggplot from the pdp data
ggp <- ggplot(pdp_days, aes(x = days_since_2011, y = yhat)) +
  geom_line(color = "#8C274C") +  # Change 'blue' to any color you prefer
  labs(title = "PDP for days_since_2011",
       x = "days_since_2011",
       y = "Partial Dependence") +
  theme_minimal()

# Display the plot
print(ggp)
```


```{r}
# Repeat for other variables
pdp_temp <- partial(rf_model, pred.var = "temp", grid.resolution = 100)

# Create a ggplot from the pdp data
ggp <- ggplot(pdp_temp, aes(x = temp, y = yhat)) +
  geom_line(color = "#8C274C") +  # Change 'blue' to any color you prefer
  labs(title = "PDP for Temperature",
       x = "Temperature",
       y = "Partial Dependence") +
  theme_minimal()

# Display the plot
print(ggp)

```


```{r}
pdp_humidity <- partial(rf_model, pred.var = "hum", grid.resolution = 100)

# Create a ggplot from the pdp data
ggp <- ggplot(pdp_humidity, aes(x = hum, y = yhat)) +
  geom_line(color = "#8C274C") +  # Change 'blue' to any color you prefer
  labs(title = "PDP for hum",
       x = "hum",
       y = "Partial Dependence") +
  theme_minimal()

# Display the plot
print(ggp)
```


```{r}
pdp_windspeed <- partial(rf_model, pred.var = "windspeed", grid.resolution = 100)

# Create a ggplot from the pdp data
ggp <- ggplot(pdp_windspeed, aes(x = windspeed, y = yhat)) +
  geom_line(color = "#8C274C") +  # Change 'blue' to any color you prefer
  labs(title = "PDP for windspeed",
       x = "windspeed",
       y = "Partial Dependence") +
  theme_minimal()

# Display the plot
print(ggp)

```
# 2. Bidimensional Partial Dependency Plot.
```{r}

```








